# Generated by Django 5.0.7 on 2024-08-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveTranscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='audio',
            field=models.FileField(null=True, upload_to='liveTranscription/'),
        ),
    ]
